### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by flavono123** [shnjp/identicon#2]
Following the usage in README, it doesn't work even importing:

```shell
$ python3
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import identicon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/identicon.py", line 242
    print 'usage: python identicon.py [CODE]....'
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'usage: python identicon.py [CODE]....')?
```

**Comment by flavono123** [comment]
It seems too out of date. Are you planning to maintain this project?

**Comment by shnjp** [comment]
Certainly, this project has not been maintained.
Porting to py3k is easy, so I think that it can be tried.
Or I think that you may be looking for another fork.

**Comment by flavono123** [comment]
@shnjp Thanks for a response and further information. 🙏 🙇 

Actually, I made another [Python identicon package](https://github.com/flavono123/identicon) which generate more [Github's style image](https://github.com/blog/1586-identicons), like that of [Ruby](https://github.com/victorgama/identicon) or [Elixir](https://github.com/rbishop/identicon)  or [Javascript](https://github.com/stewartlord/identicon.js) version.

I'm trouble with upload that to PyPI since the same package name with this repository(The rule is case insensitive).

As you've mentioned not plan to maintain this, would you remind to give me the package name?

Fill free to suggest any idea on this problem 😆

**Comment by shnjp** [comment]
oh! This is a nice library.

And I did not know that this library is registered with PyPi.
If you know the deletion method, I will proceed if you can tell me.
Do I have to ask Package Index Owner?

**Comment by flavono123** [comment]
@shnjp I simply guessed you are the owner but not..! 😂 

I have to contact the owner.

Thanks! Your kind comment was helpful. 🙇 

May I notice the proceed or any help on this issue? 🤔

**Comment by flavono123** [comment]
@shnjp Thanks for your comment and kindness! 🙇

I simply guessed you are the owner but not..! 😂

I found his(Ross Kinder) email: ross@kndr.org

Deletion seems could be done by the owner, here is [the method(2nd answer with screenshot also helpful)](https://stackoverflow.com/questions/20403387/how-to-remove-a-package-from-pypi)

And it would be great if you contact to him, and that looks make sense I think 😂

**Comment by flavono123** [comment]
@shnjp No response from the owner? 🤔

**Comment by flavono123** [comment]
Or could I contact to him? 🤔

**Comment by shnjp** [comment]
I'm sorry, I am taking a vacation.
I will mail him

**Comment by crewjam** [comment]
Happy to help. 

I packaged up the module for pypi ages ago, and I too am no longer using it personally. Rather than delete, I think the right thing to do is to transfer ownership to one or both of you. To do that it appears I need to know your pypi user names. 

![image](https://user-images.githubusercontent.com/5651547/36379056-2af0fa0e-154b-11e8-94c2-a8ed42f890fd.png)

**Comment by flavono123** [comment]
@shnjp @crewjam 
Great! 

It would be happy to me that [my repository](https://github.com/flavono123/identicon) gonna be a PyPI package named `identicon`.

btw, my PyPI user name is flavono123

**Comment by crewjam** [comment]
Okay @flavono123 you are now an owner of the package in pypi. I think that means you'll be able to upload a new version etc.

**Comment by flavono123** [comment]
Thanks for helps! 

Then, @shnjp, you agree with that [my project](https://github.com/flavono123/identicon) gonna be the PyPI `identicon` package?

**Comment by flavono123** [comment]
I published my repo: 
https://pypi.python.org/pypi/identicon/0.1

Thank you all and If you have any suggestion, feel free to contact me by flavono123@gmail.com

😆
